version: "3.9" # version of the docker-compose synttax

services: 
  app: # name of our service
    build: # build a docker file inside a current dir
      context: . # root dir that currently running from
    ports:
      - "8000:8000" # how we access network when we connect to our server
    volumes: # the way of mapping dir from our system to a docker container
      - ./app:/app #automatically syncs the code to the container
    command: > # the default command used to run the service
      sh -c "python manage.py runserver 0.0.0.0:8000"


# version: "3.9"

# services:
#   app:
#     build:
#       context: .
#       args:
#         - DEV=true
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./app:/app
#       - dev-static-data:/vol/web
#     command: >
#       sh -c "python manage.py wait_for_db &&
#              python manage.py migrate &&
#              python manage.py runserver 0.0.0.0:8000"
#     environment:
#       - DB_HOST=db
#       - DB_NAME=devdb
#       - DB_USER=devuser
#       - DB_PASS=changeme
#       - DEBUG=1
#     depends_on:
#       - db

#   db:
#     image: postgres:13-alpine
#     volumes:
#       - dev-db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=devdb
#       - POSTGRES_USER=devuser
#       - POSTGRES_PASSWORD=changeme

# volumes:
#   dev-db-data:
#   dev-static-data: