# Generated by Django 4.2.4 on 2023-09-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
