# Generated by Django 4.2.4 on 2023-10-30 08:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userprofile_gender_alter_userprofile_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to=core.models.image_file_path),
        ),
    ]
