# Generated by Django 4.2.4 on 2023-10-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userprofile_dob_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default='YYYY-MM-DD', null=True),
        ),
    ]
