"""
URL mappings for the recipe app.
"""
from django.urls import (
    path,  # used to define path
    include,  # used to include URLs by names
)
# use this with APIView to automatically create routes
# for all the different options vailable for that view.
from rest_framework.routers import DefaultRouter
from recipe import views

# create a default router
router = DefaultRouter()

# register viewset with that router with name 'recipes'
# it will assign all endpoints from RecipeViewSet to that endpoint
router.register('recipes', views.RecipeViewSet)
router.register('tags', views.TagViewSet)

app_name = 'recipe'  # used for reverse lookup of URLs

urlpatterns = [
    path('', include(router.urls)),  # include urls generated by router
]
