--- # signifies that this is a yml file
name: Checks # name that will apper in GH Actions

on: [push] # trigger

jobs:
    test-lint: # id of the job
        name: Test and Lint
        runs-on: ubuntu-20.04 # os that jobs are run on
        steps: # things that run for the job

            ## STEP 1
            - name: Login to Docker Hub # this name is seen in GH Actions
                    # docker container/configuration that set up to perform a task @ verion of the action
              uses: docker/login-action@v1 # use premade action from GH Actions repository
              with: # pass in the parameters
                # passed into Docker login action that's gonna login to Docker with these credentials
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            ## STEP 2
            # after step 1 is successful, the 2nd one below is run
            - name: Checkout
              uses: actions/checkout@v2 # checks our code

            ## STEP 3
            - name: Test
              # run a unittest
              # runs wait_for_db before test
              run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test" # test: command that is used to run the tests in our project

            ## STEP 4
            - name: Lint
              run: docker-compose run --rm app sh -c "flake8"
